name: Run python script and commit updates

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # this step checks out your repository code

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pandas numpy

    - name: Run python script
      run: python main.py

    - name: Pull master. Commit and push if data changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git pull origin master --rebase
        git diff
        git commit -am "Data updated" || echo "No changes to commit"
        git push
